use('restaurants');
db.restaurants.find();
db.restaurants.find({},{"restaurant_id":true, "name":true,"borough":true, "cuisine":true});
db.restaurants.find({},{"_id":false, "restaurant_id":true, "name":true,"borough":true, "cuisine":true});
db.restaurants.find({},{"_id":false, "restaurant_id":true, "name":true,"borough":true, "address.zipcode":true});
db.restaurants.find({},{"_id":false, "borough": "Bronx", "name":true});
db.restaurants.find({},{"_id":false, "borough": "Bronx", "name":true}).limit(5);
db.restaurants.find({},{"_id":false, "borough": "Bronx", "name":true}).skip(5).limit(5);
db.restaurants.find({"grades.score": {$gt:90}}, {"name": true, "grades.score": true});
db.restaurants.find({"grades.score": {$gt:80, $lt:100}},{"name":1, "grades.score": true});
db.restaurants.find({"address.coord": {$lt:-95.754168}},{"name":1, "address.coord": true});
db.restaurants.find({"cuisine": {$ne:"American", $ne: "American "}, "grades.score": {$gt:70}, "address.coord": {$lt:-65.754168}},{"name":true, "cuisine": true, "grades.score": true, "address.coord": true});
db.restaurants.find({"cuisine": {$ne:"American", $ne: "American "}, "grades.score": {$gt:70}, "address.coord": {$lt:-65.754168}}, {"cuisine": true, "address.coord": true, "grades.score": true});
db.restaurants.find({"cuisine": {$ne:"American", $ne: "American "}, "grades.grade": {$eq:"A"}, "borough": {$ne:"Brooklyn"}},{"borough":true, "grades.grade": true, "cuisine": true}).sort({"cuisine":-1});
db.restaurants.find({"name":/^Wil/},{"_id":false, "restaurant_id": true, "name": true, "borough": true, "cuisine": true});
db.restaurants.find({"name":/ces$/},{"_id":false, "restaurant_id": true, "name": true, "borough": true, "cuisine": true});
db.restaurants.find({"name":/Reg/},{"_id":false, "restaurant_id": true, "name": true, "borough": true, "cuisine": true});
db.restaurants.find({$or: [ {"cuisine": {$eq: "American "}},{"cuisine": {$eq: "Chinese"}} ],  "borough": {$eq: "Bronx"} },{"_id":false, "borough": true, "name": true, "borough": true, "cuisine": true});
db.restaurants.find({$or: [{"borough": {$eq: "Bronx"}},{"borough": {$eq: "Staten Island"}},{"borough": {$eq: "Queens"}},{"borough": {$eq: "Brooklyn"}}]},{"_id":false, "restaurant_id": true, "name": true, "borough": true, "cuisine": true});
db.restaurants.find({$and: [{"borough": {$ne: "Bronx"}},{"borough": {$ne: "Staten Island"}},{"borough": {$ne: "Queens"}},{"borough": {$ne: "Brooklyn"}}]},{"_id":false, "restaurant_id": true, "name": true, "borough": true, "cuisine": true});
db.restaurants.find({"grades.score": {$lt:10}} ,{"_id":false, "restaurant_id": true, "name": true, "borough": true, "cuisine": true});
